export const STATUS_RDV = {
  PLANIFIE: "PLANIFIE",
  TERMINE: "TERMINE",
  ANNULE: "ANNULE",
  PATIENT_ABSENT: "PATIENT_ABSENT",
};

export const VILLES = [
  { label: "Agadir", value: "AGADIR" },
  { label: "Al Hoceima", value: "AL_HOCEIMA" },
  { label: "Asilah", value: "ASILAH" },
  { label: "Azemmour", value: "AZEMMOUR" },
  { label: "Azilal", value: "AZILAL" },
  { label: "Beni Mellal", value: "BENI_MELLAL" },
  { label: "Berkane", value: "BERKANE" },
  { label: "Berrechid", value: "BERRECHID" },
  { label: "Boujdour", value: "BOUJDOUR" },
  { label: "Casablanca", value: "CASABLANCA" },
  { label: "Chefchaouen", value: "CHEFCHAOUEN" },
  { label: "Dakhla", value: "DAKHLA" },
  { label: "El Hajeb", value: "EL_HAJEB" },
  { label: "El Jadida", value: "EL_JADIDA" },
  { label: "Errachidia", value: "ERRACHIDIA" },
  { label: "Essaouira", value: "ESSAOUIRA" },
  { label: "Fès", value: "FES" },
  { label: "Fquih Ben Salah", value: "FQUIH_BEN_SALAH" },
  { label: "Guelmim", value: "GUELMIM" },
  { label: "Ifrane", value: "IFRANE" },
  { label: "Kalaat M'Gouna", value: "KALAAT_MGOUNA" },
  { label: "Kénitra", value: "KENITRA" },
  { label: "Khénifra", value: "KHENIFRA" },
  { label: "Khouribga", value: "KHOURIBGA" },
  { label: "Ksar El Kebir", value: "KSAR_EL_KEBIR" },
  { label: "Laâyoune", value: "LAAYOUNE" },
  { label: "Larache", value: "LARACHE" },
  { label: "Marrakech", value: "MARRAKECH" },
  { label: "Martil", value: "MARTIL" },
  { label: "Meknès", value: "MEKNES" },
  { label: "Midelt", value: "MIDELT" },
  { label: "Mohammedia", value: "MOHAMMEDIA" },
  { label: "Nador", value: "NADOR" },
  { label: "Ouarzazate", value: "OUARZAZATE" },
  { label: "Oujda", value: "OUJDA" },
  { label: "Rabat", value: "RABAT" },
  { label: "Safi", value: "SAFI" },
  { label: "Salé", value: "SALE" },
  { label: "Sefrou", value: "SEFROU" },
  { label: "Settat", value: "SETTAT" },
  { label: "Sidi Ifni", value: "SIDI_IFNI" },
  { label: "Sidi Kacem", value: "SIDI_KACEM" },
  { label: "Sidi Slimane", value: "SIDI_SLIMANE" },
  { label: "Skhirat", value: "SKHIRAT" },
  { label: "Tanger", value: "TANGER" },
  { label: "Taourirt", value: "TAOURIRT" },
  { label: "Tarfaya", value: "TARFAYA" },
  { label: "Taroudant", value: "TAROUDANT" },
  { label: "Taza", value: "TAZA" },
  { label: "Temara", value: "TEMARA" },
  { label: "Tétouan", value: "TETOUAN" },
  { label: "Tiznit", value: "TIZNIT" },
  { label: "Zagora", value: "ZAGORA" },
];

export const Status = [
  { label: "APTE", value: "Apte" },
  { label: "NON_APTE", value: "Non Apte" },
  { label: "EN_ATTENTE_DE_REEVALUATION", value: "En Attente de Réévaluation" },
  { label: "EXAMEN_ANNUEL_A_PREVOIR", value: "Examen Annuel à Prévoir" },
];
